version: '3.8'
services:

  ############
  # FRONTEND #
  ############

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - "php"
    networks:
      default:
        aliases:
          - perfin.docker
    volumes:
      - ./www:/var/www:delegated
      - ./build/nginx/sites:/etc/nginx/conf.d:cached
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    logging:
      driver: "local"
      options:
        max-size: "10m"
  
  #######
  # PHP #
  #######

  php:
    build:
      context: build/php/8.1
    image: perfin/php:8.1
    volumes:
      - ./www:/var/www:delegated
      - ~/.ssh:/root/.ssh:cached
    working_dir: /var/www
    logging:
      driver: "local"
      options:
        max-size: "10m"

  #############
  # SERVICES  #
  #############

  postgresql:
    image: postgres:14.5-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: perfin
    logging:
      driver: "local"
      options:
        max-size: "10m"

  redis:
    image: redis:7.0.5-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    logging:
      driver: "local"
      options:
        max-size: "10m"
volumes:
  postgresql-data:
    driver: local
  redis-data:
    driver: local
